import type { ModuleDeclaration } from '@duefold/composition/contract';

export const moduleDeclaration: ModuleDeclaration = {
  id: 'core-security',
  packageName: '@duefold/core-security',
  requires: [],
  routes: [
    {
      id: 'health.live',
      method: 'GET',
      path: '/api/health/live',
      audience: 'public',
      handler: 'routes/health-live.ts',
    },
    {
      id: 'health.ready',
      method: 'GET',
      path: '/api/health/ready',
      audience: 'public',
      handler: 'routes/health-ready.ts',
      handlerFactoryExport: 'createReadinessHandler',
    },
    {
      id: 'auth.session',
      method: 'GET',
      path: '/api/auth/session',
      audience: 'public',
      handler: 'routes/session.ts',
      handlerFactoryExport: 'createHandler',
    },
    {
      id: 'auth.oidc.begin',
      method: 'GET',
      path: '/api/auth/oidc/begin',
      audience: 'public',
      handler: 'routes/oidc-begin.ts',
      handlerFactoryExport: 'createHandler',
    },
    {
      id: 'auth.oidc.callback',
      method: 'GET',
      path: '/api/auth/oidc/callback',
      audience: 'public',
      handler: 'routes/oidc-callback.ts',
      handlerFactoryExport: 'createHandler',
    },
    {
      id: 'auth.otp.request',
      method: 'POST',
      path: '/api/auth/otp/request',
      audience: 'public',
      csrf: false,
      handler: 'routes/otp-request.ts',
      handlerFactoryExport: 'createHandler',
    },
    {
      id: 'auth.otp.verify',
      method: 'POST',
      path: '/api/auth/otp/verify',
      audience: 'public',
      csrf: false,
      handler: 'routes/otp-verify.ts',
      handlerFactoryExport: 'createHandler',
    },
    {
      id: 'auth.sign-out.member',
      method: 'POST',
      path: '/api/auth/member/sign-out',
      audience: 'member',
      handler: 'routes/sign-out.ts',
      handlerFactoryExport: 'createHandler',
    },
    {
      id: 'auth.sign-out.viewer',
      method: 'POST',
      path: '/api/auth/viewer/sign-out',
      audience: 'viewer',
      handler: 'routes/sign-out.ts',
      handlerFactoryExport: 'createHandler',
    },
    {
      id: 'auth.sign-out-all.member',
      method: 'POST',
      path: '/api/auth/member/sign-out-all',
      audience: 'member',
      handler: 'routes/sign-out.ts',
      handlerFactoryExport: 'createHandler',
    },
    {
      id: 'auth.sign-out-all.viewer',
      method: 'POST',
      path: '/api/auth/viewer/sign-out-all',
      audience: 'viewer',
      handler: 'routes/sign-out.ts',
      handlerFactoryExport: 'createHandler',
    },
    {
      id: 'organization.members.list',
      method: 'GET',
      path: '/api/members',
      audience: 'member',
      handler: 'routes/member-list.ts',
      handlerFactoryExport: 'createHandler',
    },
    {
      id: 'organization.members.actions',
      method: 'POST',
      path: '/api/members/actions',
      audience: 'member',
      handler: 'routes/member-actions.ts',
      handlerFactoryExport: 'createHandler',
    },
    {
      id: 'installation.status.read',
      method: 'GET',
      path: '/api/status',
      audience: 'member',
      handler: 'routes/deployment-status.ts',
      handlerFactoryExport: 'createHandler',
    },
  ],
  migrations: [
    { id: '001_security_kernel', file: '001_security_kernel.sql' },
    { id: '017_organization_administration', file: '017_organization_administration.sql' },
    { id: '024_deployment_status', file: '024_deployment_status.sql' },
  ],
  jobs: [
    {
      id: 'mail.viewer_invitation',
      handler: 'jobs/required-mail-delivery.ts',
      handlerFactoryExport: 'createHandler',
      service: 'worker',
    },
    {
      id: 'mail.member_invitation',
      handler: 'jobs/member-invitation-mail.ts',
      handlerFactoryExport: 'createHandler',
      service: 'worker',
    },
    {
      id: 'auth.otp.deliver',
      handler: 'jobs/otp-delivery.ts',
      handlerFactoryExport: 'createHandler',
      service: 'worker',
    },
    {
      id: 'ownership.preview.purge',
      handler: 'jobs/ownership-preview-purge.ts',
      handlerFactoryExport: 'createHandler',
      service: 'worker',
    },
  ],
  config: [
    {
      key: 'DUEFOLD_DATABASE_URL',
      kind: 'secret',
      required: true,
      service: 'web',
      description: 'PostgreSQL connection string for the runtime role.',
    },
    {
      key: 'DUEFOLD_AUTH_DATABASE_URL',
      kind: 'secret',
      required: true,
      service: 'web',
      description:
        'PostgreSQL connection string for the isolated authentication-evidence and session-lifecycle role.',
    },
    {
      key: 'DUEFOLD_WORKER_DATABASE_URL',
      kind: 'secret',
      required: true,
      service: 'worker',
      description: 'PostgreSQL connection string for the worker role.',
    },
    {
      key: 'DUEFOLD_MIGRATION_DATABASE_URL',
      kind: 'secret',
      required: true,
      service: 'cli',
      description: 'PostgreSQL connection string for the migration role.',
    },
    {
      key: 'DUEFOLD_PUBLIC_URL',
      kind: 'url',
      required: true,
      service: 'shared',
      description: 'Absolute external base URL.',
    },
    {
      key: 'DUEFOLD_OIDC_ISSUER',
      kind: 'url',
      required: true,
      service: 'web',
      description: 'Generic OIDC issuer URL.',
    },
    {
      key: 'DUEFOLD_OIDC_CLIENT_ID',
      kind: 'string',
      required: true,
      service: 'web',
      description: 'OIDC client identifier.',
    },
    {
      key: 'DUEFOLD_OIDC_CLIENT_AUTH_METHOD',
      kind: 'enum',
      required: false,
      service: 'web',
      default: 'auto',
      values: ['auto', 'client_secret_post', 'client_secret_basic'],
      description:
        'OIDC token endpoint client authentication: automatic discovery-based selection or an explicit confidential-client method.',
    },
    {
      key: 'DUEFOLD_OIDC_CLIENT_SECRET',
      kind: 'secret',
      required: true,
      service: 'web',
      description: 'OIDC client secret.',
    },
    {
      key: 'DUEFOLD_OWNER_EMAIL_ALLOWLIST',
      kind: 'string',
      required: true,
      service: 'web',
      description: 'Comma-separated exact normalized bootstrap owner emails.',
    },
    {
      key: 'DUEFOLD_ORGANIZATION_NAME',
      kind: 'string',
      required: true,
      service: 'web',
      description: 'Organization name used for first-owner bootstrap.',
    },
    {
      key: 'DUEFOLD_OTP_DIGEST_KEY',
      kind: 'secret',
      required: true,
      service: 'shared',
      description: 'Key used only for OTP keyed digests.',
    },
    {
      key: 'DUEFOLD_NETWORK_HMAC_KEY',
      kind: 'secret',
      required: true,
      service: 'web',
      description: 'Key used with monthly period separation for network HMACs.',
    },
    {
      key: 'DUEFOLD_SMTP_URL',
      kind: 'secret',
      required: false,
      service: 'shared',
      description:
        'SMTP connection URL. Required only when the reviewed composition selects the SMTP adapter.',
    },
    {
      key: 'DUEFOLD_RESEND_API_KEY',
      kind: 'secret',
      required: false,
      service: 'shared',
      description:
        'Resend API key. Required only when the reviewed composition selects the Resend adapter.',
    },
    {
      key: 'DUEFOLD_AUTH_MAIL_FROM',
      kind: 'string',
      required: true,
      service: 'shared',
      description: 'From address for authentication mail.',
    },
    {
      key: 'DUEFOLD_ALLOW_DB_RESET',
      kind: 'boolean',
      required: false,
      service: 'cli',
      default: false,
      description: 'Explicit operator guard for destructive local database reset.',
    },
    {
      key: 'DUEFOLD_PORT',
      kind: 'number',
      required: false,
      service: 'web',
      default: 8080,
      description:
        'TCP port the web service listens on. Platforms that assign a port (Railway, Heroku) supply it; keep the default behind a reverse proxy.',
    },
    {
      key: 'DUEFOLD_SESSION_IDLE_MINUTES',
      kind: 'number',
      required: false,
      service: 'web',
      default: 30,
      description: 'Session idle lifetime, constrained to 5-60 minutes.',
    },
    {
      key: 'DUEFOLD_SESSION_ABSOLUTE_HOURS',
      kind: 'number',
      required: false,
      service: 'web',
      default: 12,
      description: 'Session absolute lifetime, constrained to 1-24 hours.',
    },
    {
      key: 'DUEFOLD_TRUSTED_PROXIES',
      kind: 'string',
      required: false,
      service: 'web',
      description:
        'Trusted reverse proxy configuration: hop count (e.g. "1") or comma-separated CIDRs/IPs (e.g. "127.0.0.1,10.0.0.0/8"). Off by default.',
    },
  ],
  browserEntries: [],
};
