/**
 * `rooms-documents` owns the private document lifecycle boundary.
 */
import type { ModuleDeclaration } from '@duefold/composition/contract';

export const moduleDeclaration: ModuleDeclaration = {
  id: 'rooms-documents',
  packageName: '@duefold/rooms-documents',
  requires: ['core-security'],
  routes: [
    {
      id: 'room.list',
      method: 'GET',
      path: '/api/rooms',
      audience: 'member',
      handler: 'routes/room-list.ts',
      handlerFactoryExport: 'createHandler',
    },
    {
      id: 'room.workspace.read',
      method: 'GET',
      path: '/api/rooms/workspace',
      audience: 'member',
      handler: 'routes/room-workspace.ts',
      handlerFactoryExport: 'createHandler',
    },
    {
      id: 'room.structure.mutate',
      method: 'POST',
      path: '/api/rooms/structure',
      audience: 'member',
      handler: 'routes/structure-mutate.ts',
      handlerFactoryExport: 'createHandler',
    },
    {
      id: 'room.action',
      method: 'POST',
      path: '/api/rooms/actions',
      audience: 'member',
      handler: 'routes/room-actions.ts',
      handlerFactoryExport: 'createHandler',
    },
    {
      id: 'viewer.room.list',
      method: 'GET',
      path: '/api/viewer/rooms',
      audience: 'viewer',
      handler: 'routes/viewer-room-list.ts',
      handlerFactoryExport: 'createHandler',
    },
    {
      id: 'viewer.structure.read',
      method: 'GET',
      path: '/api/viewer/structure',
      audience: 'viewer',
      handler: 'routes/viewer-structure.ts',
      handlerFactoryExport: 'createHandler',
    },
    {
      id: 'viewer.structure.search',
      method: 'GET',
      path: '/api/viewer/search',
      audience: 'viewer',
      handler: 'routes/viewer-search.ts',
      handlerFactoryExport: 'createHandler',
    },
    {
      id: 'viewer.document.read',
      method: 'GET',
      path: '/api/viewer/document',
      audience: 'viewer',
      handler: 'routes/viewer-document.ts',
      handlerFactoryExport: 'createHandler',
    },
    {
      id: 'protected.link.interstitial',
      method: 'GET',
      path: '/api/viewer/links/interstitial',
      audience: 'viewer',
      handler: 'routes/safe-link-interstitial.ts',
      handlerFactoryExport: 'createHandler',
    },
    {
      id: 'protected.page.create',
      method: 'POST',
      path: '/api/viewer/pages/cache',
      audience: 'viewer',
      handler: 'routes/protected-page-create.ts',
      handlerFactoryExport: 'createHandler',
    },
    {
      id: 'protected.page.deliver',
      method: 'GET',
      path: '/api/viewer/pages/image',
      audience: 'viewer',
      handler: 'routes/protected-page-deliver.ts',
      handlerFactoryExport: 'createHandler',
    },
    {
      id: 'protected.page.text',
      method: 'GET',
      path: '/api/viewer/pages/text',
      audience: 'viewer',
      handler: 'routes/protected-text.ts',
      handlerFactoryExport: 'createHandler',
    },
    {
      id: 'preview.begin',
      method: 'POST',
      path: '/api/viewer/previews',
      audience: 'viewer',
      handler: 'routes/preview-begin.ts',
      handlerFactoryExport: 'createHandler',
    },
    {
      id: 'preview.heartbeat',
      method: 'POST',
      path: '/api/viewer/previews/heartbeat',
      audience: 'viewer',
      handler: 'routes/preview-heartbeat.ts',
      handlerFactoryExport: 'createHandler',
    },
    {
      id: 'preview.close',
      method: 'POST',
      path: '/api/viewer/previews/close',
      audience: 'viewer',
      handler: 'routes/preview-close.ts',
      handlerFactoryExport: 'createHandler',
    },
    {
      id: 'download.lease.create',
      method: 'POST',
      path: '/api/viewer/downloads',
      audience: 'viewer',
      handler: 'routes/download-lease.ts',
      handlerFactoryExport: 'createHandler',
    },
    {
      id: 'download.range',
      method: 'GET',
      path: '/api/viewer/downloads/range',
      audience: 'viewer',
      handler: 'routes/download-range.ts',
      handlerFactoryExport: 'createHandler',
    },
    {
      id: 'room.lifecycle',
      method: 'POST',
      path: '/api/rooms/lifecycle',
      audience: 'member',
      handler: 'routes/lifecycle.ts',
      handlerFactoryExport: 'createHandler',
    },
    {
      id: 'export.list',
      method: 'GET',
      path: '/api/exports',
      audience: 'member',
      handler: 'routes/export-list.ts',
      handlerFactoryExport: 'createHandler',
    },
    {
      id: 'export.manage',
      method: 'POST',
      path: '/api/exports',
      audience: 'member',
      handler: 'routes/exports.ts',
      handlerFactoryExport: 'createHandler',
    },
    {
      id: 'export.download',
      method: 'POST',
      path: '/api/exports/download',
      audience: 'member',
      handler: 'routes/export-download.ts',
      handlerFactoryExport: 'createHandler',
    },
    {
      id: 'upload.intent.create',
      method: 'POST',
      path: '/api/uploads/intents',
      audience: 'member',
      handler: 'routes/upload-intent.ts',
      handlerFactoryExport: 'createHandler',
    },
    {
      id: 'upload.intent.finalize',
      method: 'POST',
      path: '/api/uploads/finalize',
      audience: 'member',
      handler: 'routes/upload-finalize.ts',
      handlerFactoryExport: 'createHandler',
    },
    {
      id: 'document.processing.state',
      method: 'GET',
      path: '/api/documents/processing',
      audience: 'member',
      handler: 'routes/processing-state.ts',
      handlerFactoryExport: 'createHandler',
    },
    {
      id: 'document.processing.retry',
      method: 'POST',
      path: '/api/documents/processing-retry',
      audience: 'member',
      handler: 'routes/processing-retry.ts',
      handlerFactoryExport: 'createHandler',
    },
    {
      id: 'document.failed-source.delete',
      method: 'DELETE',
      path: '/api/documents/failed-source',
      audience: 'member',
      handler: 'routes/failed-source-delete.ts',
      handlerFactoryExport: 'createHandler',
    },
  ],
  migrations: [
    { id: '002_private_content', file: '002_private_content.sql' },
    { id: '003_processing_pipeline', file: '003_processing_pipeline.sql' },
    { id: '004_room_structure', file: '004_room_structure.sql' },
    { id: '005_trash_search_bulk', file: '005_trash_search_bulk.sql' },
    { id: '006_member_workspace_readers', file: '006_member_workspace_readers.sql' },
    { id: '008_protected_delivery', file: '008_protected_delivery.sql' },
    { id: '009_viewer_discovery', file: '009_viewer_discovery.sql' },
    { id: '010_exports', file: '010_exports.sql' },
    { id: '011_retention_lifecycle', file: '011_retention_lifecycle.sql' },
    { id: '014_member_state_readers', file: '014_member_state_readers.sql' },
  ],
  jobs: [
    {
      id: 'document.source.validate',
      handler: 'jobs/source-validation.ts',
      handlerFactoryExport: 'createHandler',
      service: 'worker',
    },
    {
      id: 'upload.multipart.reap',
      handler: 'jobs/multipart-reap.ts',
      handlerFactoryExport: 'createHandler',
      service: 'worker',
    },
    {
      id: 'document.derivative.cleanup',
      handler: 'jobs/derivative-cleanup.ts',
      handlerFactoryExport: 'createHandler',
      service: 'worker',
    },
    {
      id: 'download.lease.finalize',
      handler: 'jobs/download-finalizer.ts',
      handlerFactoryExport: 'createHandler',
      service: 'worker',
    },
    {
      id: 'preview.inactivity.finalize',
      handler: 'jobs/preview-inactivity.ts',
      handlerFactoryExport: 'createHandler',
      service: 'worker',
    },
    {
      id: 'document.watermark.delete',
      handler: 'jobs/watermark-cleanup.ts',
      handlerFactoryExport: 'createHandler',
      service: 'worker',
    },
    {
      id: 'room.trash.purge',
      handler: 'jobs/trash-purge.ts',
      handlerFactoryExport: 'createHandler',
      service: 'worker',
    },
    {
      id: 'room.whole.purge',
      handler: 'jobs/room-purge.ts',
      handlerFactoryExport: 'createHandler',
      service: 'worker',
    },
    {
      id: 'document.retention.sweep',
      handler: 'jobs/retention-sweep.ts',
      handlerFactoryExport: 'createHandler',
      service: 'worker',
    },
    {
      id: 'export.generate',
      handler: 'jobs/export-generation.ts',
      handlerFactoryExport: 'createHandler',
      service: 'worker',
    },
    {
      id: 'export.cleanup',
      handler: 'jobs/export-cleanup.ts',
      handlerFactoryExport: 'createHandler',
      service: 'worker',
    },
  ],
  config: [
    {
      key: 'DUEFOLD_STORAGE_ENDPOINT',
      kind: 'url',
      required: true,
      service: 'shared',
      description: 'S3-compatible endpoint.',
    },
    {
      key: 'DUEFOLD_STORAGE_REGION',
      kind: 'string',
      required: true,
      service: 'shared',
      description: 'S3 signing region.',
    },
    {
      key: 'DUEFOLD_STORAGE_BUCKET',
      kind: 'string',
      required: true,
      service: 'shared',
      description: 'Private content bucket.',
    },
    {
      key: 'DUEFOLD_STORAGE_PATH_STYLE',
      kind: 'boolean',
      required: false,
      service: 'shared',
      default: false,
      description: 'Use S3 path-style addressing.',
    },
    {
      key: 'DUEFOLD_STORAGE_CHECKSUM_SUPPORT',
      kind: 'boolean',
      required: false,
      service: 'shared',
      default: true,
      description: 'Require native multipart SHA-256 checksums.',
    },
    {
      key: 'DUEFOLD_STORAGE_WEB_ACCESS_KEY_ID',
      kind: 'secret',
      required: true,
      service: 'web',
      description: 'Write-only web storage access key.',
    },
    {
      key: 'DUEFOLD_STORAGE_WEB_SECRET_ACCESS_KEY',
      kind: 'secret',
      required: true,
      service: 'web',
      description: 'Write-only web storage secret.',
    },
    {
      key: 'DUEFOLD_STORAGE_WORKER_ACCESS_KEY_ID',
      kind: 'secret',
      required: true,
      service: 'worker',
      description: 'Quarantine-reading worker storage access key.',
    },
    {
      key: 'DUEFOLD_STORAGE_WORKER_SECRET_ACCESS_KEY',
      kind: 'secret',
      required: true,
      service: 'worker',
      description: 'Quarantine-reading worker storage secret.',
    },
    {
      key: 'DUEFOLD_CLAMAV_HOST',
      kind: 'string',
      required: true,
      service: 'shared',
      description: 'Private ClamAV INSTREAM host.',
    },
    {
      key: 'DUEFOLD_CLAMAV_PORT',
      kind: 'number',
      required: true,
      service: 'shared',
      description: 'Private ClamAV INSTREAM port.',
    },
    {
      key: 'DUEFOLD_PROCESSOR_OFFICE_PROGRAM',
      kind: 'string',
      required: true,
      service: 'worker',
      description: 'Sandboxed LibreOffice 25.2 executable.',
    },
    {
      key: 'DUEFOLD_PROCESSOR_PDF_PROGRAM',
      kind: 'string',
      required: true,
      service: 'worker',
      description: 'Sandboxed PDF processor executable.',
    },
    {
      key: 'DUEFOLD_WATERMARK_IMAGE_PROGRAM',
      kind: 'string',
      required: true,
      service: 'web',
      description: 'Web-only ImageMagick executable for protected-page watermarks.',
    },
    {
      key: 'DUEFOLD_PROCESSOR_IMAGE_PROGRAM',
      kind: 'string',
      required: true,
      service: 'worker',
      description: 'Sandboxed image processor executable.',
    },
    {
      key: 'DUEFOLD_PROCESSOR_TEXT_PROGRAM',
      kind: 'string',
      required: true,
      service: 'worker',
      description: 'Sandboxed text/CSV processor executable.',
    },
    {
      key: 'DUEFOLD_SANDBOX_MODE',
      kind: 'enum',
      required: true,
      service: 'worker',
      values: ['production', 'development'],
      description: 'Production requires every sandbox isolation feature.',
    },
    {
      key: 'DUEFOLD_SANDBOX_ISOLATION',
      kind: 'enum',
      required: false,
      default: 'namespaced',
      service: 'shared',
      values: ['namespaced', 'degraded'],
      description:
        'How untrusted document parsing is launched. Degraded drops filesystem, network, and PID isolation for hosts whose runtime denies namespace creation; it keeps the credential-free environment and no-new-privileges. Never selected automatically.',
    },
    {
      key: 'DUEFOLD_SANDBOX_DEVELOPMENT_ACKNOWLEDGEMENT',
      kind: 'string',
      required: false,
      service: 'worker',
      description: 'Explicit non-production sandbox acknowledgement.',
    },
    {
      key: 'DUEFOLD_SANDBOX_DEGRADED_ACKNOWLEDGEMENT',
      kind: 'string',
      required: false,
      service: 'shared',
      description:
        'Required verbatim when DUEFOLD_SANDBOX_ISOLATION=degraded. A second independent statement, so degraded isolation cannot be enabled by setting one variable while skimming a guide.',
    },
    {
      key: 'DUEFOLD_PII_HMAC_KEY',
      kind: 'secret',
      required: false,
      service: 'worker',
      description:
        'Independent worker-only key for stable room-scoped viewer evidence references; required by worker startup and omitted from web/CLI environments.',
    },
    {
      key: 'DUEFOLD_UPDATE_PUBLIC_KEY_PATH',
      kind: 'string',
      required: false,
      service: 'cli',
      description: 'Pinned Ed25519 public-key PEM path for signed release manifest checks.',
    },
  ],
  browserEntries: [],
};
